### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by XeonCorp** [weeco/supercell-packet-listener#3]
Hello, weeco. Please share the captured packets of Brawl Stars 7.278. I'm very needed it to create Retro Brawl Stars Server. Please answer!!!!!! @weeco

**Comment by XeonCorp** [comment]
@weeco  pls answer

**Comment by weeco** [comment]
@XeonCorp I don't owe you an answer. I don't work on BrawlStats or any other Supercell game anymore
